= le  Web,  ses  Frameworks  et ses  Standards : déconstruire pour mieux (re?)construire...
Hubert Sablonnière
:author-twitter: @hsablonniere
:author-avatar: img/hsablonniere-profil-2017.jpg
:author-company: Clever Cloud
:author-company-logo: img/clever-cloud-logo.svg
:event: DevoxxFR
:date: 17 avril 2019

[slide=poster]
Poster

[slide=blank]
Fondu vers le noir

[.old]
== Prologue...

#Mettre la musique (Jazzopedie)#
#Voix off, grave, triste#
Perdu dans la jungle du Web moderne, de ses frameworks et ses standards, notre personnage principal est perdu.
Depuis le début de sa carrière, au fil des semaines, des mois et des années... il voit naitre tous ces nouveaux outils révolutionnaires et prometteurs mais qui demain seront délaissés et remplacés par de nouveaux encore plus mieux.

[slide=todo]
logos et noms des frameworks avec RIP et pierres tombales (laisser un espace oh milieu)

C'est avec tristesse et mélancholie qu'il repense à tous ces frameworks, librairies, éditeurs de code et autres outils en ligne de commande...
#Un peu de respect pour les disparus SVP!#

[slide=todo]
react, angular et vue dans le centre du coolitude radar

...qui s'ils n'ont pas déjà disparu de nos projets ont déjà disparu de nos radars de coolitude.
Cette situation l'inquiète, le questionne et l'empêche de dormir.
Dans le cadre de son travail, il doit faire des choix techniques mais il ne sais plus quoi faire.
C'est à ce moment là que notre personnage pris la décision d'aller voir un thérapeuthe.

[slide=todo]
tete des personnages qui vont se parler

// Musique
😎 Bonjour docteur.
👩‍⚕️ Bonjour Monsieur Sablonnière, alors, qu'est-ce qui vous amène ?
👩‍⚕️ La dernière fois que je vous ai vu, c'était il y a bien 10 ans...
👩‍⚕️ Vous commenciez votre premier job et vous étiez en pleine crise existentielle sur "est-ce qu'il faut utiliser des espaces ou des tabulations" et sur la "prononciation des guiffes animé"...
😎 Des jifs, vous voulez-dire ?
😎 Non mais ça c'est du passé, j'étais jeune et débutant, je ne me posais pas les bonnes questions.

[slide=todo]
Personnage H qui pense que les espaces c'est mieux.

😎 Aujourd'hui, je prends du recul sur le monde du frontend Web et je fais un constat :
😎 Les effets de mode et de hype nous rendent beaucoup trop dépendant de nos outils.
👩‍⚕️ Humm, dites mois en plus, je vois pas trop quel problèmes ça implique.

[slide=todo]
Problème numéro 1

// illustrer les pb avec des tweets

😎 Problème numéro 1...
👩‍⚕️ Euh... quand on vous pose une question, vous répondez toujours en sortant un PowerPoint ?

[slide=todo]
Personnage H qui pense "mais j'utilise pas PowerPoint en plus"

😎 Bah ouais pourquoi, je vois pas le problème. Bref.

[slide=todo]
Problème numéro 1

😎 Problème numéro 1...
😎 Quand on choisi un framework (ou une lib) frontend
//, mais finalement, c'est assez vrai avec n'importe quel outil,
😎 on en oublie souvent le problème qu'on voulait résoudre à la base et pourtant on a l'impression d'avoir trouvé la bonne réponse, la solution à utiliser.
😎 Parfois, c'était le bon outil et parfois la solution est adaptée à des problèmes qu'on a pas vraiment.
👩‍⚕️ Mais pourquoi vous faites ça ?
😎 Parfois le choix se fait parceque la techno est cool (DX vs UX)
😎 Parfois parcequ'elle est utilisée/créée par un géant du Web
😎 Les recruteurs demandent tous cet outil, du coup, on se forme dessus, c'est un cercle qui s'auto alimente
😎 Il y a des confs sur le sujet et des meetups, ça doit forcément être bien
😎 Et pourtant vous n'avez peut-être pas le même contexte que les gens qui trouvent cette solution utile
// Analogie de la voiture
// À force d'utiliser nos voitures, on en oublie qu'à la base on avait un problème, on veut se déplacer
// en oubliant se problème, on en vient à utiliser tout le temps la même solution sans se soucier des paramètres de départ
// et on finit par aller acheter du pain à 500m en polluant la planète.
// Aaahhh

[slide=todo]
Problème numéro 2

😎 Problème numéro 2...
😎 On fois qu'on a choisi un ecosystème (fwk/lib), on a tendance à s'enferme dedans
😎 On cherche systématiquement comment faire X ou Y avec l'écosystème foo alors que X ou Y sont universels (jQuery)
😎 On code l'énième version de feature/composant X ou Y pour cet écosystème
😎 Difficile de revenir en arrière quand on a investi du temps d'apprentissage
😎 On ne voit plus les défauts de nos propres outils
😎 On soutient des fonctionnalités sans les comprendre
😎 On ne regarde pas ce qui se fait ailleurs avec un oeil ouvert
😎 On compare un framework tel qu'Angular aux Web Components, ça n'a aucun sens
😎 On rempli nos cerveaux avec des noms de features (au lieu de les remplir avec des noms de pattern)
// Analogie conférences Apple

[slide=todo]
Problème numéro 3

😎 Problème numéro 3...
😎 On produit du code qui subit mal les effets du temps
😎 Les changements de son propre ecosystème
😎 Du code trop couplé au framework lui même
😎 L'arrivée de nouveaux standards
😎 Du code qui mélange les couches (souvent car on ne voit pas en quoi c'est un problème)
😎 Voire même sa disparition
😎 On jette à la poubelle plein de connaissances
😎 On jette à la poubelle plein de code
// On s'est laissé aller à produire du code qui rentre dans les clous de nos outils plutôt que d'exiger de nos outils qu'ils proposent des branchements pour s'adapter à notre code.
// Analogie de la TV

[slide=todo]
Visages qui parlent

// Attention à ne pas être trop négatif
À la base, ces outils sont censés nous aider
C'est encore, le cas, je reste persuadé que le ratio de ce qu'ils apportent et des problèmes que j'évoque est du côté positif mais cela ne m'empêche pas de m'inquiéter.
// Bon, j'ai pas tout compris alors
// je vous prescris une thérapie de groupe
// vous allez m'analyser tous ces trucs en détails comme vous savez faire
// vous allez réunir un groupe de personnes qui bossent dans votre domaine (un bon groupe de 800, c'est bien)
// et vous leur partagez vos préoccupation, votre analyse et votre démarche
// wow, mais ça fait peur non ?
// Allez, ça va bien se passer

[slide=poster]
Bonjour à *toutes* et tous !
J'm'appelle Hubert Sablonnière,
J'suis développeur Web chez #Clever Cloud#,
et aujourd'hui, j'ai envie de vous parler :
du Web,
de ses frameworks et autres librairies
et de ses standards.

== *Comment* en est-on  arrivé là ?

[slide=todo]
schéma ères du web (vide)

[slide=todo]
schéma ères du web (old school ssr)

[slide=todo]
schéma ères du web (images)

[slide=todo]
schéma ères du web (forms)
// interactivité

[slide=todo]
schéma ères du web (SSR + JS)
// ajout du JS
// validation de form

[slide=todo]
schéma ères du web (AJAX with jQuery)

[slide=todo]
schéma ères du web (SPA era, client side templating)

[slide=todo]
schéma ères du web (SPA era, routing)
// anchor/hash => push state

[slide=todo]
schéma ères du web (the mega bundle era with empty body)

[slide=todo]
schéma ères du web (SSR + hydratation + code splitting)

== C'était quoi  le *problème* ?

== Ce que les *frameworks*  nous apportent ?

== *Séparons* nos  préoccupations

== Ce que les *standards*  nous apportent ?

Est-ce que votre outil est prêt demain à adopter un standard et jetter son implem pour vous faire profiter du support natif ?

== La solution  *parfaite* !

== Ce que le *futur*  nous réserve...

[.old]
== ...Epilogue

// Revenir sur les problèmes et les solutions qu'on y a apporté
Ne vous enfermez pas dans un framework/écosystème !
Analysez les briques qui composent ce framework/écosystème, leur rôle et les avantages/inconvénients qu'il apporte
Intéressez vous aux standards pour savoir comment ils impacteront demain vos choix d'aujourd'hui
Découpler, isoler, séparer pour mieux maitriser (perf, sécu) s'adapter au futur
Intéressez vous à ce qui se fait dans tous ces écosystèmes (en particulier si vous êtes partisan du NIH et que vous avez votre propre framework)

.merci  beaucoup !
[slide=poster]
Outro

//[slide=question]
//Questions ?
