= le  Web,  ses  Frameworks  et ses  Standards : déconstruire pour mieux (re?)construire...
Hubert Sablonnière
:author-twitter: @hsablonniere
:author-avatar: img/hsablonniere-profil-2017.jpg
:author-company: Clever Cloud
:author-company-logo: img/clever-cloud-logo.svg
:hashtags: #WebFrameworks
:event: DevoxxFR
:date: 17 avril 2019
:city: Paris

[slide=poster]
Intro

[slide=blank]
Fondu vers le noir

[.old]
== Prologue...
// Mettre la musique (Jazzopedie)

#Grosse voix off#
Perdu dans la jungle du Web moderne, ses frameworks, ses standards, ses outils, ses modes qui vont et qui viennent...
Notre personnage principal était perdu.
Il repensait à tous ces outils qu'il avait utilisé depuis le début de sa carrière et qui aujourd'hui avaient disparus.

[slide=todo]
logos et noms des frameworks avec RIP et pierres tombales

Ayant de besoin de prendre une décision pour son projet chez Clever Cloud,
notre personnage principal alla voir un thérapeuthe.
// Musique

[slide=todo]
tete des personnages

H: Bonjour docteur.
D: Bonjour Monsieur Sablonnière, alors, qu'est-ce qui vous amène cette fois-ci ?
D: La dernière fois que je vous ai vu, c'était il y a bien 10 ans.
D: Vous commenciez votre premier job et vous étiez en pleine crise existentielle sur "est-ce qu'il faut utiliser des espaces ou des tabulations" et sur la "prononciation du mot guiffes animé"...
H: Des jifs, vous voulez-dire ?
H: Non mais ça c'est du passé, j'étais jeune et débutant, je ne me posais pas les bonnes questions.

[slide=todo]
Personnage H qui pense que les espaces c'est mieux.

D: Bon alors c'est quoi votre problème cette fois ci du coup ?

[slide=todo]
Problème numéro 1

H: Problème numéro 1...
D: Euh... quand on vous pose une question, vous répondez toujours en sortant un PowerPoint ?

[slide=todo]
Personnage H qui pense "mais j'utilise pas PowerPoint en plus"

H: Bah ouais pourquoi, je vois pas le problème.
H: Bref.

[slide=todo]
Problème numéro 1

H: Problème numéro 1...
H: On choisit des outils mais on a oublié les problèmes qu'on essaye de résoudre
et en plus, on utilise parfois des solutions adaptés à des problèmes qu'on a pas vraiment.
// Analogie de la voiture
// À force d'utiliser nos voitures, on en oublie qu'à la base on avait un problème, on veut se déplacer
// en oubliant se problème, on en vient à utiliser tout le temps la même solution sans se soucier des paramètres de départ
// et on finit par aller acheter du pain à 500m en polluant la planète.
// Aaahhh

[slide=todo]
Problème numéro 2

H: Problème numéro 2...
H: On choisi des outils par effet de mode, un peu trop souvent à mon goût par interêt pour le développeur plus que pour l'utilisateur.
H: Vendor lockin, hype, CV, meetups, communautés
// Isolation en silo
// Analogie de la voiture
// Analogie conférences Apple

[slide=todo]
Problème numéro 3

H: Problème numéro 3...
H: Quand un écosystème disparait, devient moins pertinent
H: On jette à la poubelle plein de connaissances
H: On jette à la poubelle plein de code
H: Du coup, on a du mal à remplacer une partie sans jeter le reste
// On s'est laissé aller à produire du code qui rentre dans les clous de nos outils plutôt que d'exiger de nos outils qu'ils proposent des branchements pour s'adapter à notre code.
// On a trop couplé notre code métier au outils qu'on utilise
// Analogie de la TV

[slide=todo]
Problème numéro 4

H: Problème numéro 4...
H: Quand un standard arrive on s'en fout un peu, on passe à côté.
H: On a oublié que moins on ship de code mieux c'est pour l'utilisateur.
// Sizzle, ajax, promise (voir tweet)
// Analogie de la voiture

== *Comment* en est-on  arrivé là ?

[slide=todo]
schéma ères du web (vide)

[slide=todo]
schéma ères du web (old school ssr)

[slide=todo]
schéma ères du web (images)

[slide=todo]
schéma ères du web (forms)
// interactivité

[slide=todo]
schéma ères du web (SSR + JS)
// ajout du JS
// validation de form

[slide=todo]
schéma ères du web (AJAX with jQuery)

[slide=todo]
schéma ères du web (SPA era, client side templating)

[slide=todo]
schéma ères du web (SPA era, routing)
// anchor/hash => push state

[slide=todo]
schéma ères du web (the mega bundle era with empty body)

[slide=todo]
schéma ères du web (SSR + hydratation + code splitting)

== C'était quoi  le *problème* ?

== Ce que les *frameworks*  nous apportent ?

== *Séparons* nos  préoccupations

== Ce que les *standards*  nous apportent ?

Est-ce que votre outil est prêt demain à adopter un standard et jetter son implem pour vous faire profiter du support natif ?

== La solution  *parfaite* !

== Ce que le *futur*  nous réserve...

[.old]
== ...Epilogue

// Revenir sur les problèmes et les solutions qu'on y a apporté

.merci  beaucoup !
[slide=poster]
Outro

* Ne vous enfermez pas dans un framework/écosystème !
* Analysez les briques qui composent ce framework/écosystème, leur rôle et les avantages/inconvénients qu'il apporte
* Intéressez vous aux standards pour savoir comment ils impacteront demain vos choix d'aujourd'hui
* Découpler, isoler, séparer pour mieux maitriser (perf, sécu) s'adapter au futur
* Intéressez vous à ce qui se fait dans tous ces écosystèmes (en particulier si vous êtes partisan du NIH et que vous avez votre propre framework)

//[slide=question]
//Questions ?
